import { useState } from 'react';
import { Sun, Download, Copy, Check, RefreshCw, Info } from 'lucide-react';

const WEATHER_PRESETS = [
  { name: 'غروب نارنجی', ambR: 200, ambG: 120, ambB: 60, skyTopR: 255, skyTopG: 100, skyTopB: 30, skyBotR: 255, skyBotG: 200, skyBotB: 80, sunR: 255, sunG: 200, sunB: 100 },
  { name: 'شب تاریک', ambR: 20, ambG: 20, ambB: 40, skyTopR: 5, skyTopG: 5, skyTopB: 20, skyBotR: 10, skyBotG: 10, skyBotB: 30, sunR: 100, sunG: 100, sunB: 200 },
  { name: 'طوفان رعد', ambR: 60, ambG: 60, ambB: 80, skyTopR: 40, skyTopG: 40, skyTopB: 60, skyBotR: 70, skyBotG: 70, skyBotB: 90, sunR: 200, sunG: 200, sunB: 255 },
  { name: 'صبح بهاری', ambR: 180, ambG: 200, ambB: 220, skyTopR: 100, skyTopG: 180, skyTopB: 255, skyBotR: 200, skyBotG: 230, skyBotB: 255, sunR: 255, sunG: 250, sunB: 200 },
  { name: 'بیابان داغ', ambR: 255, ambG: 200, ambB: 140, skyTopR: 255, skyTopG: 200, skyTopB: 100, skyBotR: 255, skyBotG: 240, skyBotB: 180, sunR: 255, sunG: 255, sunB: 200 },
  { name: 'مه صبحگاهی', ambR: 160, ambG: 160, ambB: 160, skyTopR: 180, skyTopG: 190, skyTopB: 200, skyBotR: 220, skyBotG: 225, skyBotB: 230, sunR: 240, sunG: 240, sunB: 240 },
  { name: 'بارانی', ambR: 80, ambG: 90, ambB: 100, skyTopR: 60, skyTopG: 70, skyTopB: 90, skyBotR: 100, skyBotG: 110, skyBotB: 130, sunR: 150, sunG: 160, sunB: 180 },
  { name: 'شب نارنجی (SA-MP)', ambR: 120, ambG: 60, ambB: 20, skyTopR: 40, skyTopG: 20, skyTopB: 10, skyBotR: 80, skyBotG: 40, skyBotB: 15, sunR: 255, sunG: 140, sunB: 50 },
];

interface TCValues {
  ambR: number; ambG: number; ambB: number;
  dirR: number; dirG: number; dirB: number;
  skyTopR: number; skyTopG: number; skyTopB: number;
  skyBotR: number; skyBotG: number; skyBotB: number;
  sunR: number; sunG: number; sunB: number;
  sunIntensity: number;
  shadowIntensity: number;
  blurLevel: number;
  fogLevel: number;
}

const DEFAULT_VALUES: TCValues = {
  ambR: 150, ambG: 120, ambB: 100,
  dirR: 200, dirG: 160, dirB: 120,
  skyTopR: 100, skyTopG: 150, skyTopB: 220,
  skyBotR: 200, skyBotG: 210, skyBotB: 240,
  sunR: 255, sunG: 240, sunB: 200,
  sunIntensity: 50,
  shadowIntensity: 100,
  blurLevel: 0,
  fogLevel: 0,
};

function generateTimecycleLine(v: TCValues): string {
  return [
    v.ambR, v.ambG, v.ambB,
    v.dirR, v.dirG, v.dirB,
    v.skyTopR, v.skyTopG, v.skyTopB,
    v.skyBotR, v.skyBotG, v.skyBotB,
    v.sunR, v.sunG, v.sunB, '0.04',
    '0', '0', '0',
    v.shadowIntensity, '80', '60',
    '50', '200', '150', '100',
    '0.0', v.blurLevel, '0.0', '0.0',
    v.fogLevel, '0.0', '-1.0',
  ].join('   ');
}

function generateFullTimecycle(v: TCValues): string {
  const times = ['Sunrise', 'Morning', 'Noon', 'Afternoon', 'Sunset', 'Evening', 'Night', 'Midnight'];
  const weathers = Array.from({ length: 12 }, (_, i) => `Weather ${i + 1}`);

  let output = '// GTA San Andreas TimeCycle\n// Generated by SAMP Tools — @XchoR MMD\n\n';

  for (const weather of weathers) {
    output += `// ${weather}\n`;
    for (const time of times) {
      output += generateTimecycleLine(v) + '\n';
    }
    output += '\n';
  }

  return output;
}

export default function Timecycle() {
  const [values, setValues] = useState<TCValues>(DEFAULT_VALUES);
  const [customCode, setCustomCode] = useState('');
  const [useCustom, setUseCustom] = useState(false);
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);

  function set(key: keyof TCValues, val: number) {
    setValues(prev => ({ ...prev, [key]: val }));
  }

  function applyPreset(p: typeof WEATHER_PRESETS[0]) {
    setValues(prev => ({ ...prev, ...p }));
  }

  function generate() {
    if (useCustom && customCode.trim()) {
      // Parse the custom code and apply color modification
      const lines = customCode.split('\n');
      const modified = lines.map(line => {
        const parts = line.trim().split(/\s+/);
        if (parts.length < 3) return line;
        // Modify first 3 values (ambient RGB) with our color
        parts[0] = String(values.ambR);
        parts[1] = String(values.ambG);
        parts[2] = String(values.ambB);
        if (parts.length > 6) {
          parts[6] = String(values.skyTopR);
          parts[7] = String(values.skyTopG);
          parts[8] = String(values.skyTopB);
        }
        return parts.join('   ');
      });
      setOutput(modified.join('\n'));
    } else {
      setOutput(generateFullTimecycle(values));
    }
  }

  function download() {
    const blob = new Blob([output || generateFullTimecycle(values)], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'timecyc.dat';
    a.click();
  }

  function copy() {
    navigator.clipboard.writeText(output || generateFullTimecycle(values));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  const skyStyle = {
    background: `linear-gradient(to bottom, rgb(${values.skyTopR},${values.skyTopG},${values.skyTopB}), rgb(${values.skyBotR},${values.skyBotG},${values.skyBotB}))`,
  };

  return (
    <div className="space-y-5">
      <div className="flex gap-3 p-4 bg-blue-500/10 border border-blue-500/20 rounded-xl">
        <Info size={16} className="text-blue-400 shrink-0 mt-0.5" />
        <p className="text-xs text-gray-300 font-rajdhani">
          رنگ و تنظیمات دلخواه را انتخاب کنید. فایل <strong className="text-orange-400">timecyc.dat</strong> با آن رنگ برای همه آب و هواهای GTA SA تولید می‌شود.
          یا کد قدیمی خود را paste کنید و رنگ روی اون اعمال بشه.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
        {/* Controls */}
        <div className="space-y-4">
          {/* Preview sky */}
          <div className="card overflow-hidden p-0">
            <div className="h-24 rounded-t-xl" style={skyStyle} />
            <div className="p-3">
              <p className="text-xs font-rajdhani text-gray-400 text-center">پیش‌نمایش آسمان</p>
              <div className="flex items-center justify-center gap-3 mt-2">
                <div className="flex items-center gap-1.5">
                  <div className="w-3 h-3 rounded-full" style={{ backgroundColor: `rgb(${values.sunR},${values.sunG},${values.sunB})` }} />
                  <span className="text-[10px] text-gray-500 font-rajdhani">خورشید</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <div className="w-3 h-3 rounded-full" style={{ backgroundColor: `rgb(${values.ambR},${values.ambG},${values.ambB})` }} />
                  <span className="text-[10px] text-gray-500 font-rajdhani">محیط</span>
                </div>
              </div>
            </div>
          </div>

          {/* Presets */}
          <div className="card">
            <h3 className="font-rajdhani font-bold text-orange-500 text-sm mb-3">پریست‌های آب و هوا</h3>
            <div className="grid grid-cols-1 gap-1.5">
              {WEATHER_PRESETS.map(p => (
                <button
                  key={p.name}
                  onClick={() => applyPreset(p)}
                  className="flex items-center gap-2 p-2 bg-dark-300 border border-dark-50 rounded-lg hover:border-orange-500/30 transition-all group text-left"
                >
                  <div className="w-6 h-6 rounded flex-shrink-0" style={{ background: `linear-gradient(135deg, rgb(${p.skyTopR},${p.skyTopG},${p.skyTopB}), rgb(${p.skyBotR},${p.skyBotG},${p.skyBotB}))` }} />
                  <span className="text-xs font-rajdhani text-gray-400 group-hover:text-white transition-colors">{p.name}</span>
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Sliders */}
        <div className="space-y-4">
          {/* Custom code input */}
          <div className="card">
            <div className="flex items-center justify-between mb-3">
              <h3 className="font-rajdhani font-bold text-white text-sm">کد timecyc.dat سفارشی</h3>
              <button
                onClick={() => setUseCustom(b => !b)}
                className={`relative w-10 h-5 rounded-full transition-colors ${useCustom ? 'bg-orange-500' : 'bg-dark-50'}`}
              >
                <div className={`absolute top-0.5 w-4 h-4 rounded-full bg-white transition-transform ${useCustom ? 'left-5' : 'left-0.5'}`} />
              </button>
            </div>
            {useCustom && (
              <textarea
                value={customCode}
                onChange={e => setCustomCode(e.target.value)}
                placeholder="کد timecyc.dat قدیمی را اینجا paste کنید..."
                className="w-full h-28 bg-dark-400 border border-dark-50 rounded-lg p-3 text-xs font-mono text-green-400 focus:outline-none focus:border-orange-500/50 resize-none"
                dir="ltr"
              />
            )}
          </div>

          {/* RGB Sliders */}
          {[
            { label: 'نور محیط (Ambient)', keys: ['ambR', 'ambG', 'ambB'] as const, color: 'from-yellow-500/20 to-yellow-600/10' },
            { label: 'بالای آسمان (SkyTop)', keys: ['skyTopR', 'skyTopG', 'skyTopB'] as const, color: 'from-blue-500/20 to-blue-600/10' },
            { label: 'پایین آسمان (SkyBottom)', keys: ['skyBotR', 'skyBotG', 'skyBotB'] as const, color: 'from-cyan-500/20 to-cyan-600/10' },
            { label: 'رنگ خورشید (Sun)', keys: ['sunR', 'sunG', 'sunB'] as const, color: 'from-orange-500/20 to-orange-600/10' },
          ].map(({ label, keys, color }) => (
            <div key={label} className={`card bg-gradient-to-br ${color}`}>
              <h4 className="text-xs font-rajdhani font-bold text-white mb-3">{label}</h4>
              {(['R', 'G', 'B'] as const).map((ch, i) => {
                const key = keys[i];
                const colors = ['bg-red-500', 'bg-green-500', 'bg-blue-500'];
                return (
                  <div key={ch} className="flex items-center gap-2 mb-2">
                    <span className={`w-4 h-4 rounded text-[10px] flex items-center justify-center ${colors[i]} text-white font-bold shrink-0`}>{ch}</span>
                    <input
                      type="range" min="0" max="255"
                      value={values[key]}
                      onChange={e => set(key, Number(e.target.value))}
                      className="flex-1 accent-orange-500"
                    />
                    <span className="text-xs text-gray-400 font-mono w-8 text-right">{values[key]}</span>
                  </div>
                );
              })}
            </div>
          ))}

          {/* Extra settings */}
          <div className="card space-y-3">
            {[
              { label: 'سایه', key: 'shadowIntensity' as const, min: 0, max: 255 },
              { label: 'مه', key: 'fogLevel' as const, min: 0, max: 255 },
              { label: 'بلور', key: 'blurLevel' as const, min: 0, max: 100 },
            ].map(({ label, key, min, max }) => (
              <div key={key} className="flex items-center gap-2">
                <span className="text-xs text-gray-400 font-rajdhani w-14 shrink-0">{label}</span>
                <input type="range" min={min} max={max} value={values[key]} onChange={e => set(key, Number(e.target.value))} className="flex-1 accent-orange-500" />
                <span className="text-xs text-gray-400 font-mono w-8 text-right">{values[key]}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Output */}
        <div className="space-y-4">
          <div className="flex gap-2">
            <button onClick={generate} className="btn-orange flex-1 flex items-center justify-center gap-2">
              <RefreshCw size={15} /> تولید کد
            </button>
          </div>

          {output ? (
            <>
              <div className="card p-3">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-mono text-orange-400">timecyc.dat</span>
                  <span className="text-[10px] text-gray-500 font-rajdhani">{output.split('\n').length} خط</span>
                </div>
                <pre className="bg-dark-400 rounded-lg p-3 text-[10px] text-green-400 font-mono h-64 overflow-auto whitespace-pre leading-relaxed">
                  {output.slice(0, 2000)}...
                </pre>
              </div>

              <div className="flex gap-2">
                <button onClick={download} className="btn-orange flex-1 flex items-center justify-center gap-2">
                  <Download size={15} /> دانلود .dat
                </button>
                <button onClick={copy} className="btn-outline flex items-center justify-center gap-2 px-4">
                  {copied ? <Check size={15} className="text-green-400" /> : <Copy size={15} />}
                  {copied ? 'کپی!' : 'کپی'}
                </button>
              </div>
            </>
          ) : (
            <div className="card flex flex-col items-center justify-center py-12 text-center">
              <Sun size={32} className="text-gray-700 mb-3" />
              <p className="text-sm text-gray-500 font-rajdhani">رنگ‌ها را تنظیم کن</p>
              <p className="text-xs text-gray-600 mt-1 font-rajdhani">سپس «تولید کد» بزن</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
