import { useState } from 'react';
import { Download, Zap, RefreshCw, Star, Copy, Check, Info } from 'lucide-react';

interface WeaponConfig {
  name: string;
  nameEn: string;
  id: number;
  damage: number;
  range: number;
  fireRate: number;
  accuracy: number;
  clipSize: number;
  reloadTime: number;
  enabled: boolean;
}

const DEFAULT_WEAPONS: WeaponConfig[] = [
  { id: 22, name: 'پیستول', nameEn: 'Pistol', damage: 35, range: 35, fireRate: 500, accuracy: 85, clipSize: 17, reloadTime: 1200, enabled: true },
  { id: 23, name: 'پیستول صدا خفه‌کن', nameEn: 'Silenced Pistol', damage: 40, range: 35, fireRate: 500, accuracy: 90, clipSize: 17, reloadTime: 1200, enabled: true },
  { id: 24, name: 'دیزرت ایگل', nameEn: 'Desert Eagle', damage: 70, range: 35, fireRate: 700, accuracy: 75, clipSize: 7, reloadTime: 1500, enabled: true },
  { id: 25, name: 'شات‌گان', nameEn: 'Shotgun', damage: 100, range: 40, fireRate: 1000, accuracy: 60, clipSize: 8, reloadTime: 2000, enabled: true },
  { id: 26, name: 'ساونیف', nameEn: 'Sawnoff', damage: 80, range: 25, fireRate: 700, accuracy: 50, clipSize: 2, reloadTime: 1200, enabled: true },
  { id: 27, name: 'کامبت شات‌گان', nameEn: 'Combat Shotgun', damage: 90, range: 35, fireRate: 400, accuracy: 65, clipSize: 8, reloadTime: 1600, enabled: true },
  { id: 28, name: 'یوزی', nameEn: 'UZI', damage: 25, range: 35, fireRate: 100, accuracy: 55, clipSize: 50, reloadTime: 1000, enabled: true },
  { id: 29, name: 'MP5', nameEn: 'MP5', damage: 30, range: 45, fireRate: 80, accuracy: 70, clipSize: 30, reloadTime: 1000, enabled: true },
  { id: 30, name: 'کلاش (AK-47)', nameEn: 'AK-47', damage: 35, range: 70, fireRate: 90, accuracy: 70, clipSize: 30, reloadTime: 1200, enabled: true },
  { id: 31, name: 'M4', nameEn: 'M4', damage: 30, range: 90, fireRate: 80, accuracy: 80, clipSize: 30, reloadTime: 1000, enabled: true },
  { id: 32, name: 'تک-9', nameEn: 'Tec-9', damage: 20, range: 30, fireRate: 100, accuracy: 50, clipSize: 50, reloadTime: 800, enabled: true },
  { id: 33, name: 'تفنگ کانتری', nameEn: 'Country Rifle', damage: 75, range: 100, fireRate: 1200, accuracy: 90, clipSize: 1, reloadTime: 2000, enabled: true },
  { id: 34, name: 'اسنایپر', nameEn: 'Sniper Rifle', damage: 100, range: 120, fireRate: 1500, accuracy: 98, clipSize: 1, reloadTime: 2000, enabled: true },
  { id: 35, name: 'RPG', nameEn: 'RPG', damage: 200, range: 200, fireRate: 2000, accuracy: 95, clipSize: 1, reloadTime: 3000, enabled: true },
  { id: 41, name: 'اسپری', nameEn: 'Spraycan', damage: 5, range: 10, fireRate: 50, accuracy: 60, clipSize: 500, reloadTime: 500, enabled: true },
];

const PRESETS = [
  {
    name: 'نقش‌بازی رئالیستی (Roleplay)', icon: '🎭',
    desc: 'آسیب کم، دقت بالا، فاصله متوسط',
    mods: { damage: 0.7, range: 1.0, fireRate: 1.2, accuracy: 1.1, clipSize: 1.0, reloadTime: 1.3 },
  },
  {
    name: 'دث‌مچ (DeathMatch)', icon: '💀',
    desc: 'آسیب بالا، فاصله زیاد، سریع',
    mods: { damage: 1.5, range: 1.3, fireRate: 0.7, accuracy: 0.9, clipSize: 1.5, reloadTime: 0.7 },
  },
  {
    name: 'استاندارد SA-MP', icon: '🎮',
    desc: 'تنظیمات پیش‌فرض بازی',
    mods: { damage: 1.0, range: 1.0, fireRate: 1.0, accuracy: 1.0, clipSize: 1.0, reloadTime: 1.0 },
  },
  {
    name: 'فری‌رومِ شاد', icon: '🌟',
    desc: 'تفریحی — آسیب متعادل',
    mods: { damage: 1.2, range: 1.1, fireRate: 0.9, accuracy: 1.0, clipSize: 1.3, reloadTime: 0.9 },
  },
  {
    name: 'سرور جنگ (War)', icon: '⚔️',
    desc: 'حداکثر آسیب و سرعت',
    mods: { damage: 2.0, range: 1.5, fireRate: 0.5, accuracy: 0.85, clipSize: 2.0, reloadTime: 0.5 },
  },
  {
    name: 'پولیس و دزد', icon: '🚓',
    desc: 'متعادل برای سرورهای RP پلیس',
    mods: { damage: 0.9, range: 1.2, fireRate: 1.0, accuracy: 1.2, clipSize: 1.0, reloadTime: 1.1 },
  },
];

// Generate weapon.dat line for a weapon
function generateWeaponLine(w: WeaponConfig): string {
  const slot = w.id >= 22 && w.id <= 24 ? 2 : w.id >= 25 && w.id <= 27 ? 3 : w.id >= 28 && w.id <= 32 ? 4 : w.id >= 33 && w.id <= 34 ? 5 : w.id === 35 ? 6 : 1;
  // GTA SA weapon.dat simplified format
  return [
    w.nameEn.toLowerCase().replace(' ', '_'),
    w.id, w.id,
    slot,
    w.range.toFixed(1), w.range.toFixed(1),
    '2', // fire type
    '0.0', '0.6', '-0.1', // offsets
    w.damage,
    w.clipSize,
    w.reloadTime,
    w.fireRate,
    w.accuracy.toFixed(2),
    '1.0', '0', '0', '0', '0',
    '0.0', '50.0', '2', '0.4',
    '0', '0', '0', '0',
    '0', '0', '0',
    '0', '0.0', '0',
    'false', 'false', 'false', 'false', 'false', 'false', 'false',
  ].join('\t');
}

function generateWeaponDat(weapons: WeaponConfig[]): string {
  const header = `# GTA San Andreas weapon.dat
# Generated by SAMP Tools - @XchoR MMD
# Format: name model model2 slot targetRange weaponRange fireType offsetX offsetY offsetZ damage clipSize reloadTime fireRate accuracy...
#
`;
  const lines = weapons
    .filter(w => w.enabled)
    .map(w => generateWeaponLine(w))
    .join('\n');
  return header + lines + '\n';
}

export default function WeaponDat() {
  const [weapons, setWeapons] = useState<WeaponConfig[]>(DEFAULT_WEAPONS);
  const [selected, setSelected] = useState<WeaponConfig | null>(null);
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);
  const [activePreset, setActivePreset] = useState<string | null>(null);

  function applyPreset(preset: typeof PRESETS[0]) {
    setWeapons(ws => ws.map(w => ({
      ...w,
      damage: Math.round(w.damage * preset.mods.damage),
      range: Math.round(w.range * preset.mods.range),
      fireRate: Math.round(w.fireRate * preset.mods.fireRate),
      accuracy: Math.min(100, Math.round(w.accuracy * preset.mods.accuracy)),
      clipSize: Math.round(w.clipSize * preset.mods.clipSize),
      reloadTime: Math.round(w.reloadTime * preset.mods.reloadTime),
    })));
    setActivePreset(preset.name);
    setSelected(null);
  }

  function updateWeapon(id: number, key: keyof WeaponConfig, val: number | boolean) {
    setWeapons(ws => ws.map(w => w.id === id ? { ...w, [key]: val } : w));
    if (selected?.id === id) setSelected(w => w ? { ...w, [key]: val } : null);
  }

  function generate() {
    setOutput(generateWeaponDat(weapons));
  }

  function download() {
    const content = output || generateWeaponDat(weapons);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'weapon.dat';
    a.click();
  }

  function copy() {
    navigator.clipboard.writeText(output || generateWeaponDat(weapons));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  const statBar = (val: number, max: number, color: string) => (
    <div className="flex-1 h-1.5 bg-dark-400 rounded-full overflow-hidden">
      <div className={`h-full rounded-full ${color}`} style={{ width: `${Math.min(100, (val / max) * 100)}%` }} />
    </div>
  );

  return (
    <div className="space-y-5">
      {/* Info */}
      <div className="flex gap-3 p-4 bg-blue-500/10 border border-blue-500/20 rounded-xl">
        <Info size={16} className="text-blue-400 shrink-0 mt-0.5" />
        <p className="text-xs text-gray-300 font-rajdhani">
          <strong className="text-orange-400">weapon.dat</strong> فایل تنظیمات اسلحه‌های GTA SA است. در مسیر <span className="font-mono text-green-400">data/weapon.dat</span> قرار دارد.
          پریست انتخاب کنید یا هر اسلحه را جداگانه تنظیم کنید.
        </p>
      </div>

      {/* Presets */}
      <div className="card">
        <h3 className="section-title text-base">پریست‌های آماده</h3>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
          {PRESETS.map(p => (
            <button
              key={p.name}
              onClick={() => applyPreset(p)}
              className={`p-3 rounded-xl border text-left transition-all ${activePreset === p.name ? 'bg-orange-500/15 border-orange-500/40' : 'bg-dark-300 border-dark-50 hover:border-orange-500/20'}`}
            >
              <span className="text-2xl block mb-1">{p.icon}</span>
              <p className="text-xs font-rajdhani font-bold text-white leading-tight">{p.name}</p>
              <p className="text-[10px] text-gray-500 font-rajdhani mt-0.5 leading-tight">{p.desc}</p>
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
        {/* Weapons list */}
        <div className="lg:col-span-2 card">
          <h3 className="font-rajdhani font-bold text-orange-500 mb-4 flex items-center gap-2">
            <Zap size={16} /> اسلحه‌ها ({weapons.filter(w => w.enabled).length} فعال)
          </h3>
          <div className="space-y-2 max-h-96 overflow-y-auto pr-1">
            {weapons.map(w => (
              <div
                key={w.id}
                className={`p-3 rounded-xl border cursor-pointer transition-all ${selected?.id === w.id ? 'bg-orange-500/10 border-orange-500/30' : 'bg-dark-300 border-dark-50 hover:border-orange-500/20'} ${!w.enabled ? 'opacity-50' : ''}`}
                onClick={() => setSelected(w)}
              >
                <div className="flex items-center gap-3">
                  <button
                    onClick={e => { e.stopPropagation(); updateWeapon(w.id, 'enabled', !w.enabled); }}
                    className={`w-4 h-4 rounded border flex items-center justify-center shrink-0 ${w.enabled ? 'bg-orange-500 border-orange-500' : 'border-gray-600'}`}
                  >
                    {w.enabled && <Check size={10} className="text-white" />}
                  </button>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-mono text-orange-400 w-6">{w.id}</span>
                      <span className="font-rajdhani font-bold text-sm text-white">{w.name}</span>
                      <span className="text-[10px] text-gray-500 font-rajdhani">({w.nameEn})</span>
                    </div>
                    <div className="flex items-center gap-3 mt-1.5">
                      <div className="flex items-center gap-1.5 flex-1">
                        <span className="text-[9px] text-red-400 w-8 text-right font-rajdhani">آسیب</span>
                        {statBar(w.damage, 200, 'bg-red-500')}
                      </div>
                      <div className="flex items-center gap-1.5 flex-1">
                        <span className="text-[9px] text-blue-400 w-8 text-right font-rajdhani">دقت</span>
                        {statBar(w.accuracy, 100, 'bg-blue-500')}
                      </div>
                      <div className="flex items-center gap-1.5 flex-1">
                        <span className="text-[9px] text-green-400 w-8 text-right font-rajdhani">فاصله</span>
                        {statBar(w.range, 120, 'bg-green-500')}
                      </div>
                    </div>
                  </div>

                  <div className="text-right text-[10px] font-rajdhani text-gray-500 shrink-0">
                    <p>{w.clipSize} تیر</p>
                    <p>{w.damage} آسیب</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Edit panel */}
        <div className="space-y-4">
          {selected ? (
            <div className="card">
              <h3 className="font-rajdhani font-bold text-orange-500 mb-4">{selected.name}</h3>
              <div className="space-y-3">
                {[
                  { key: 'damage', label: 'آسیب', min: 1, max: 300, color: 'accent-red-500' },
                  { key: 'range', label: 'فاصله تیراندازی', min: 5, max: 200, color: 'accent-blue-500' },
                  { key: 'fireRate', label: 'تاخیر شلیک (ms)', min: 50, max: 3000 },
                  { key: 'accuracy', label: 'دقت (0-100)', min: 10, max: 100, color: 'accent-green-500' },
                  { key: 'clipSize', label: 'ظرفیت خشاب', min: 1, max: 500 },
                  { key: 'reloadTime', label: 'زمان لود (ms)', min: 200, max: 5000 },
                ].map(({ key, label, min, max }) => (
                  <div key={key}>
                    <div className="flex justify-between mb-1">
                      <label className="text-[10px] text-gray-400 font-rajdhani">{label}</label>
                      <span className="text-[10px] text-orange-400 font-mono">{(selected as any)[key]}</span>
                    </div>
                    <div className="flex gap-2">
                      <input
                        type="range" min={min} max={max}
                        value={(selected as any)[key]}
                        onChange={e => updateWeapon(selected.id, key as keyof WeaponConfig, Number(e.target.value))}
                        className="flex-1 accent-orange-500"
                      />
                      <input
                        type="number" min={min} max={max}
                        value={(selected as any)[key]}
                        onChange={e => updateWeapon(selected.id, key as keyof WeaponConfig, Number(e.target.value))}
                        className="w-16 input-dark text-xs text-center"
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div className="card flex flex-col items-center py-10 text-center">
              <Star size={28} className="text-gray-700 mb-2" />
              <p className="text-sm text-gray-500 font-rajdhani">یک اسلحه انتخاب کنید</p>
              <p className="text-xs text-gray-600 mt-1 font-rajdhani">برای ویرایش جزئیات</p>
            </div>
          )}

          {/* Generate & Download */}
          <div className="space-y-2">
            <button onClick={generate} className="btn-orange w-full flex items-center justify-center gap-2">
              <RefreshCw size={15} /> تولید weapon.dat
            </button>
            {output && (
              <>
                <button onClick={download} className="btn-orange w-full flex items-center justify-center gap-2">
                  <Download size={15} /> دانلود weapon.dat
                </button>
                <button onClick={copy} className="btn-outline w-full flex items-center justify-center gap-2">
                  {copied ? <Check size={15} className="text-green-400" /> : <Copy size={15} />}
                  {copied ? 'کپی شد!' : 'کپی کد'}
                </button>
                <div className="bg-dark-400 rounded-lg p-3 border border-dark-50">
                  <p className="text-[10px] text-green-400 font-mono leading-relaxed overflow-x-auto whitespace-pre">
                    {output.slice(0, 300)}...
                  </p>
                </div>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
